# A Machine Learning model to predict job placemant

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/Job_Placement_Data.csv')
df.head()

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0      M           67.00    Others           91.00    Others    Commerce   
1      M           79.33   Central           78.33    Others     Science   
2      M           65.00   Central           68.00   Central        Arts   
3      M           56.00   Central           52.00   Central     Science   
4      M           85.80   Central           73.60   Central    Commerce   

   degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0              58.00         Sci&Tech              No                 55.0   
1              77.48         Sci&Tech             Yes                 86.5   
2              64.00        Comm&Mgmt              No                 75.0   
3              52.00         Sci&Tech              No                 66.0   
4              73.30        Comm&Mgmt              No                 96.8   

  specialisation  mba_percent      status  
0         Mkt&HR        58.80      Placed  
1        Mkt&Fin        66.28      Placed  
2        Mkt&Fin        57.80      Placed  
3         Mkt&HR        59.43  Not Placed  
4        Mkt&Fin        55.50      Placed

In [3]:
df.isnull().sum()

gender                 0
ssc_percentage         0
ssc_board              0
hsc_percentage         0
hsc_board              0
hsc_subject            0
degree_percentage      0
undergrad_degree       0
work_experience        0
emp_test_percentage    0
specialisation         0
mba_percent            0
status                 0
dtype: int64

In [11]:
print(df['ssc_board'].unique())
print(df['hsc_board'].unique())
print(df['hsc_subject'].unique())
print(df['undergrad_degree'].unique())
print(df['specialisation'].unique())

['Others' 'Central']
['Others' 'Central']
['Commerce' 'Science' 'Arts']
['Sci&Tech' 'Comm&Mgmt' 'Others']
['Mkt&HR' 'Mkt&Fin']


In [31]:
job_df = pd.get_dummies(df, columns=['gender','ssc_board','hsc_board','hsc_subject','undergrad_degree','specialisation','work_experience','status'],drop_first=True)

In [33]:
job_df.head()

ssc_percentage  hsc_percentage  degree_percentage  emp_test_percentage  \
0           67.00           91.00              58.00                 55.0   
1           79.33           78.33              77.48                 86.5   
2           65.00           68.00              64.00                 75.0   
3           56.00           52.00              52.00                 66.0   
4           85.80           73.60              73.30                 96.8   

   mba_percent  gender_M  ssc_board_Others  hsc_board_Others  \
0        58.80         1                 1                 1   
1        66.28         1                 0                 1   
2        57.80         1                 0                 0   
3        59.43         1                 0                 0   
4        55.50         1                 0                 0   

   hsc_subject_Commerce  hsc_subject_Science  undergrad_degree_Others  \
0                     1                    0                        0   
1                     0                    1                        0   
2                     0                    0                        0   
3                     0                    1                        0   
4                     1                    0                        0   

   undergrad_degree_Sci&Tech  specialisation_Mkt&HR  work_experience_Yes  \
0                          1                      1                    0   
1                          1                      0                    1   
2                          0                      0                    0   
3                          1                      1                    0   
4                          0                      0                    0   

   status_Placed  
0              1  
1              1  
2              1  
3              0  
4              1

# Spliting dependent and independent attributes

In [34]:
X = job_df.iloc[:,:-1]
y = job_df.iloc[:, -1]

In [35]:
print(X.shape)
print(y.shape)

(215, 14)
(215,)


In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

In [44]:
X_train.shape

(150, 14)

In [49]:
X_train.head()

ssc_percentage  hsc_percentage  degree_percentage  emp_test_percentage  \
198            67.0            70.0               65.0                88.00   
82             63.0            67.0               74.0                82.00   
65             54.0            47.0               57.0                89.69   
109            52.0            63.0               65.0                86.00   
182            52.0            65.0               57.0                75.00   

     mba_percent  gender_M  ssc_board_Others  hsc_board_Others  \
198        71.96         0                 0                 0   
82         60.44         1                 0                 0   
65         57.10         1                 1                 1   
109        56.09         1                 0                 1   
182        59.81         1                 1                 1   

     hsc_subject_Commerce  hsc_subject_Science  undergrad_degree_Others  \
198                     1                    0                        1   
82                      1                    0                        0   
65                      0                    1                        0   
109                     0                    1                        0   
182                     0                    0                        1   

     undergrad_degree_Sci&Tech  specialisation_Mkt&HR  work_experience_Yes  
198                          0                      1                    0  
82                           0                      0                    0  
65                           0                      1                    0  
109                          1                      1                    1  
182                          0                      0                    1

In [50]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)


In [51]:
X_train_scaled

array([[-0.03310727,  0.35343845, -0.1115059 , ..., -0.60302269,
         1.08347268, -0.69652603],
       [-0.39605926,  0.0860197 ,  1.08719588, ..., -0.60302269,
        -0.92295821, -0.69652603],
       [-1.21270123, -1.69677196, -1.1770186 , ..., -0.60302269,
         1.08347268, -0.69652603],
       ...,
       [-0.64740351,  0.26429886,  0.02168318, ..., -0.60302269,
        -0.92295821, -0.69652603],
       [ 0.9468631 , -0.18139905, -0.21805717, ...,  1.6583124 ,
         1.08347268, -0.69652603],
       [ 0.8742727 , -0.4488178 ,  0.28806136, ..., -0.60302269,
        -0.92295821,  1.43569652]])

In [47]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

In [52]:
clf.fit(X_train, y_train)

/Users/shaikmohammadasrarahammad/Downloads/data_science/tf/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [60]:
y_pred = clf.predict(X_test)

In [61]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, y_pred)
print("The accuracy of the classifier :", score*100)

The accuracy of the classifier : 84.61538461538461


In [62]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0],
      dtype=uint8)

In [63]:
y_test

200    1
212    1
138    1
176    1
15     1
      ..
68     0
5      0
136    0
56     1
100    0
Name: status_Placed, Length: 65, dtype: uint8

Using GridSearh CV

In [64]:
from sklearn.model_selection import GridSearchCV
import numpy as np
grid_params = {"C":np.logspace(-3,3,7)}

gd_cv = GridSearchCV(clf, grid_params, cv=10)

In [65]:
gd_cv.fit(X_train, y_train)

/Users/shaikmohammadasrarahammad/Downloads/data_science/tf/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/shaikmohammadasrarahammad/Downloads/data_science/tf/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
 

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])})

In [66]:
gd_y_pred = gd_cv.predict(X_test)

In [69]:
gd_score = accuracy_score(y_test, gd_y_pred)
print('The Grid Search CV accuracy :', gd_score*100)

The Grid Search CV accuracy : 75.38461538461539


In [70]:
X_test

ssc_percentage  hsc_percentage  degree_percentage  emp_test_percentage  \
200            69.0            60.0              65.00                87.55   
212            67.0            67.0              73.00                59.00   
138            82.0            64.0              73.00                96.00   
176            59.0            60.0              56.00                55.00   
15             65.0            75.0              69.00                72.00   
..              ...             ...                ...                  ...   
68             69.7            47.0              72.70                79.00   
5              55.0            49.8              67.25                55.00   
136            47.0            59.0              64.00                78.00   
56             63.0            71.4              61.40                68.00   
100            45.0            57.0              58.00                56.39   

     mba_percent  gender_M  ssc_board_Others  hsc_board_Others  \
200        52.81         1                 1                 1   
212        69.72         1                 1                 1   
138        71.77         0                 1                 1   
176        57.90         0                 0                 1   
15         64.66         0                 0                 0   
..           ...       ...               ...               ...   
68         59.24         0                 0                 0   
5          51.58         1                 1                 1   
136        61.58         0                 0                 0   
56         66.88         1                 1                 1   
100        64.95         0                 1                 1   

     hsc_subject_Commerce  hsc_subject_Science  undergrad_degree_Others  \
200                     1                    0                        0   
212                     1                    0                        0   
138                     0                    1                        0   
176                     1                    0                        0   
15                      1                    0                        0   
..                    ...                  ...                      ...   
68                      1                    0                        0   
5                       0                    1                        0   
136                     0                    0                        0   
56                      1                    0                        0   
100                     1                    0                        0   

     undergrad_degree_Sci&Tech  specialisation_Mkt&HR  work_experience_Yes  
200                          0                      0                    0  
212                          0                      0                    1  
138                          1                      0                    1  
176                          0                      1                    0  
15                           0                      0                    1  
..                         ...                    ...                  ...  
68                           1                      1                    0  
5                            1                      0                    1  
136                          0                      0                    0  
56                           0                      0                    0  
100                          0                      1                    1  

[65 rows x 14 columns]

In [81]:
sample_pred = clf.predict([[90.0,90.0,90.00,90.55,90.81,1,1,1,1,0,0,0,0,1]])

/Users/shaikmohammadasrarahammad/Downloads/data_science/tf/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [82]:
sample_pred

array([1], dtype=uint8)